---
- name: set_fact
  set_fact:
    ceph_mon_docker_extra_env: -e DEBUG=verbose

- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-mon.service.j2"
    dest: /etc/systemd/system/ceph-mon@.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: reload systemd unit files
  shell: systemctl daemon-reload
  changed_when: false
  failed_when: false

- name: systemd start mon container
  service:
    name: ceph-mon@{{ ansible_hostname }}
    state: restarted
    enabled: yes
  changed_when: false

- name: wait for the container to run again
  command: sleep 20

- name: show container logs
  command: journalctl -u ceph-mon@{{ ansible_hostname }}

- name: fail the playbook
  fail:
    msg: "Go debug!"
