---
- name: set_fact
  set_fact:
    ceph_rgw_docker_extra_env: -e DEBUG=verbose

- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-radosgw.service.j2"
    dest: /etc/systemd/system/ceph-radosgw@.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: reload systemd unit files
  shell: systemctl daemon-reload
  changed_when: false
  failed_when: false

- name: systemd start rgw container
  service:
    name: ceph-radosgw@{{ ansible_hostname }}
    state: started
    enabled: yes
  changed_when: false

- name: wait for the container to run again
  command: sleep 20

- name: show container logs
  command: journalctl -u ceph-radosgw@{{ ansible_hostname }}

- name: fail the playbook
  fail:
    msg: "Go debug!"
