---
- name: include copy_configs.yml
  include: copy_configs.yml

- name: include start_docker_rgw.yml
  include: start_docker_rgw.yml

- name: include copy_rgw_configs.yml
  include: copy_rgw_configs.yml

- name: include debug_docker_rgw.yml
  include: debug_docker_rgw.yml
  when:
    - rgw_container_health.rc != 0
