---
- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-radosgw.service.j2"
    dest: /etc/systemd/system/ceph-radosgw@.service
    owner: "root"
    group: "root"
    mode: "0644"

# For backward compatibility
- name: disable old systemd unit ('ceph-rgw@') if present
  service:
    name: ceph-rgw@{{ ansible_hostname }}
    state: disable
  ignore_errors: true

- name: systemd start rgw container
  systemd:
    name: ceph-radosgw@{{ ansible_hostname }}
    state: started
    enabled: yes
    daemon_reload: yes

- name: get ceph rgw container id
  command: "docker ps -a -q --filter='name=ceph-rgw-{{ ansible_hostname }}'"
  register: ceph_rgw_container_id

- name: make sure ceph rgw container stays alive
  shell: |
    first_id="{{ ceph_rgw_container_id }}"
    id=$(docker ps -a -q --filter='name=ceph-rgw-{{ ansible_hostname }}')
    ! timeout 30 bash -c "while [[ $first_id == $id ]]; do continue ; done" ]]
  changed_when: false
  failed_when: false
  register: rgw_container_health

